# Generated by Django 3.1.8 on 2021-04-07 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 7, 10, 27, 4, 101459, tzinfo=utc)),
        ),
    ]
